// Copyright (C) 2023 Michel de Boer
// License: GPLv3
#pragma once
#include <QString>

namespace ATProto::ComATProtoModeration {

enum class CategoryType
{
    OZONE_VIOLENCE,
    OZONE_SEXUAL,
    OZONE_CHILD,
    OZONE_HARASSMENT,
    OZONE_MISLEADING,
    OZONE_RULE,
    OZONE_SELF_HARM,
    OZONE_OTHER
};

QString categoryTypeToTitle(CategoryType category);
QString categoryTypeToDescription(CategoryType category);

enum class ReasonType
{
    SPAM,
    VIOLATION,
    MISLEADING,
    SEXUAL,
    RUDE,
    OTHER,
    APPEAL,

    OZONE_APPEAL,
    OZONE_OTHER,

    OZONE_VIOLENCE_ANIMAL,
    OZONE_VIOLENCE_THREATS,
    OZONE_VIOLENCE_GRAPHIC_CONTENT,
    OZONE_VIOLENCE_GLORIFICATION,
    OZONE_VIOLENCE_EXTREMIST_CONTENT,
    OZONE_VIOLENCE_TRAFFICKING,
    OZONE_VIOLENCE_OTHER,

    OZONE_SEXUAL_ABUSE_CONTENT,
    OZONE_SEXUAL_NCII,
    OZONE_SEXUAL_DEEP_FAKE,
    OZONE_SEXUAL_ANIMAL,
    OZONE_SEXUAL_UNLABELED,
    OZONE_SEXUAL_OTHER,

    OZONE_CHILD_SAFETY_CSAM,
    OZONE_CHILD_SAFETY_GROOM,
    OZONE_CHILD_SAFETY_PRIVACY,
    OZONE_CHILD_SAFETY_HARASSMENT,
    OZONE_CHILD_SAFETY_OTHER,

    OZONE_HARASSMENT_TROLL,
    OZONE_HARASSMENT_TARGETED,
    OZONE_HARASSMENT_HATE_SPEECH,
    OZONE_HARASSMENT_DOXXING,
    OZONE_HARASSMENT_OTHER,

    OZONE_MISLEADING_BOT,
    OZONE_MISLEADING_IMPERSONATION,
    OZONE_MISLEADING_SPAM,
    OZONE_MISLEADING_SCAM,
    OZONE_MISLEADING_ELECTIONS,
    OZONE_MISLEADING_OTHER,

    OZONE_RULE_SITE_SECURITY,
    OZONE_RULE_PROHIBITED_SALES,
    OZONE_RULE_BAN_EVASION,
    OZONE_RULE_OTHER,

    OZONE_SELF_HARM_CONTENT,
    OZONE_SELF_HARM_ED,
    OZONE_SELF_HARM_STUNTS,
    OZONE_SELF_HARM_SUBSTANCES,
    OZONE_SELF_HARM_OTHER
};

std::vector<ReasonType> getCategoryReasons(CategoryType category);

QString reasonTypeToString(ReasonType reason);
QString reasonTypeToTitle(ReasonType reason);

}
